language: node_js
node_js:
  - '6'
  - '8'
script:
  - npm run lint
  - npm run test
before_deploy: 'yarn'
deploy:
  provider: npm
  email: domoritz@gmail.com
  api_key:
    secure: fpLeBc7FwonXJMaACLTFIKwqqkxCBUkaGk4ApSR5eJpLaZi8l+MdW46boja+5F+FdI2cbw1Zz6Q9lZ8nEcCdKrH5lehMuZCKOaxeLF72ngoyR33Rh9qYRIoKKEn5CKEwDMWentKKAOtGG+9Zs1hF0nODeYjNSKvAErD8cKxkYPXmGhP6bS/knYA+/nk22NK08mM1jlMCCB/vtW+RNS2RwAJoTcV3QNN6D38fRqci9wzI0O2FhQGCf0aHbKWjK4aVH4jHR2F3epT622MAvDK5X2KY/LyHTbNXV1E18GrXHmC5A+NEx9nCO5j5zLmBaa/2CQS5mHyBzBuq8q/vVMZyt2wLyRfLO6SvMjigObSjg7xcD23UJA9V+Og+7mfM3plcXqHE+9PsUliePcnCbMT2gPNMr51npugrkP6aDNLLSzNS6cwPKbI3I+iosMqxvCcGcM8teWDc8kewBHM7fp+fJfkXs9LZLrQ/sfpwAEICEeE5QrmAnVp87isGS1M6I+fkhIoEkAmrb8w9Qq41IOCES4pIAtm2A1g82MjFK4F/CkjiJJY3v1TlkL2+nxD1kxMSBY8yI/V72W29Z9fArl5MLXUJhsXaed7z6V7HfQeROI9mMmKxjQ3XVlxNyNHpa3VConhCbUXyth54AdwYb/S1/2zfNZImu28eR0e/NW2ec2k=
  on:
    tags: true
    repo: vega/ts-json-schema-generator
