# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript


pool:
  vmImage: 'Ubuntu 16.04'

strategy:
  maxParallel: 2  # hack
  matrix:
    node6:
      node_version: 6.x
    node10:
      node_version: 10.x

steps:
- task: NodeTool@0
  inputs:
    versionSpec: $(node_version)
  displayName: 'Install Node.js'

- script: |
    yarn
  displayName: 'Install dependencies'

- script: |
    JEST_JUNIT_OUTPUT="./test_results.xml" yarn test --ci --reporters=default --reporters=jest-junit --coverage
  displayName: 'Test'

- script: |
    yarn lint
  displayName: 'Lint'

- script: |
    yarn build
  displayName: 'Build'

- task: publishTestResults@2
  inputs:
    testResultsFiles: './test_results.xml'
    testRunTitle: 'Node $(node_version) tests'
  condition: always()
  displayName: 'Publish Test Results'

- task: PublishCodeCoverageResults@1
  inputs:
    summaryFileLocation: './coverage/cobertura-coverage.xml'
    codeCoverageTool: 'cobertura'
  displayName: 'Publish Test Coverage'

- task: Npm@1
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    command: publish
    publishEndpoint: 'npmjs'
  displayName: 'Deploy to NPM Registry'
