name: Publish Auto

on:
  push:
    branches-ignore:
      # No canary deploys for branches opened by dependabot
      - "dependabot/**"

jobs:
  publish:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"

    name: Make a release and publish to NPM
    steps:
      - uses: actions/checkout@v2

      - name: Prepare repository
        run: git fetch --unshallow --tags

      - name: Install Node dependencies
        run: yarn --frozen-lockfile

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn run release
