name: Publish Auto

on:
  push:
    branches-ignore:
      # No canary deploys for branches opened by dependabot
      - "dependabot/**"

jobs:
  publish:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"

    name: Make a release and publish to NPM
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          registry-url: "https://registry.npmjs.org"
          cache: "yarn"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install Node dependencies
        run: yarn --frozen-lockfile

      - name: Create release
        run: npm run release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
